env:
  global:
    - SAUCY: true

before_install: gem install bundler
before_script:
  - "bundle exec rake test_app"
script: "bundle exec rspec spec"
notifications:
  email:
    - nate@finelineautomation.com
branches:
  only:
    - master
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
addons:
  sauce_connect:
    username: "FineLineAutomation"
  jwt:
    secure: "P4TIInknSjQr1SjZ0NsNlhhF3AX8c+jciFXnOxW6HE0g3BbgR2XSYgajfSZKGgsXQAqoCweD0tgypd7arrYoW+3BFvGiStLUW7hGweClCslbOyE8/AI0InfXLw5jHgIziybEpyZTMK02kJuGKtCsKa/KsqlJIojyOjQ6m3kG6DA="